import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

/**
 * Digital harvest-agreement PDF (the fairness/legal layer's artifact).
 *
 * Generates a one-page agreement with pdf-lib and returns the raw bytes. The
 * deals route uploads these to the Supabase Storage `agreements` bucket and
 * saves the public URL to deals.agreement_pdf_url.
 *
 * The document states both parties, crop, quantity, final price, advance,
 * balance on delivery, harvest date, an e-sign timestamp, and an explicit
 * "0% platform commission" line.
 */

export interface AgreementData {
  dealId: string;
  agreementDate: string; // date the agreement was created (display)
  farmerName: string;
  buyerName: string;
  crop: string;
  quantityKg: number;
  pricePerKg: number; // final agreed ₹/kg
  totalAmount: number; // ₹
  advanceAmount: number; // ₹ (15%)
  balanceAmount: number; // ₹ (paid on delivery)
  harvestDate: string; // expected harvest date (display)
  esignTimestamp: string; // ISO timestamp both parties e-signed
}

export async function generateAgreementPdf(
  data: AgreementData,
): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const page = pdf.addPage([595, 842]); // A4 portrait (pt)
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const green = rgb(0.3, 0.49, 0.16);
  const dark = rgb(0.1, 0.1, 0.1);
  const grey = rgb(0.4, 0.4, 0.4);
  const margin = 50;
  let y = 792;

  const line = (
    text: string,
    opts: { size?: number; bold?: boolean; color?: typeof dark; gap?: number } = {},
  ) => {
    page.drawText(text, {
      x: margin,
      y,
      size: opts.size ?? 11,
      font: opts.bold ? bold : font,
      color: opts.color ?? dark,
    });
    y -= opts.gap ?? 18;
  };

  line("HarvestLink", { size: 22, bold: true, color: green, gap: 8 });
  line("Digital Harvest Agreement", { size: 13, bold: true, gap: 6 });
  line("Direct farmer-to-buyer contract", { size: 9, color: grey, gap: 24 });

  line(`Agreement ID: ${data.dealId}`);
  line(`Date: ${data.agreementDate}`, { gap: 24 });

  line("Parties", { size: 13, bold: true, gap: 20 });
  line(`Farmer (Seller): ${data.farmerName}`);
  line(`Buyer: ${data.buyerName}`, { gap: 24 });

  line("Terms", { size: 13, bold: true, gap: 20 });
  line(`Crop: ${data.crop}`);
  line(`Quantity: ${data.quantityKg} kg`);
  line(`Final price: Rs. ${data.pricePerKg} / kg`);
  line(`Total contract value: Rs. ${data.totalAmount}`);
  line(`Advance payable (15%): Rs. ${data.advanceAmount}`);
  line(`Balance on delivery: Rs. ${data.balanceAmount}`);
  line(`Expected harvest date: ${data.harvestDate}`, { gap: 24 });

  // The fairness headline — explicit and unmissable.
  line("Platform commission: Rs. 0 (0%). Always.", {
    size: 12,
    bold: true,
    color: green,
    gap: 28,
  });

  line("E-Signature Record", { size: 13, bold: true, gap: 20 });
  line(`[X] Farmer e-signed: ${data.farmerName}`);
  line(`[X] Buyer e-signed: ${data.buyerName}`);
  line(`Signed at: ${data.esignTimestamp}`, { gap: 28 });

  line(
    "By e-signing, both parties agree to the quantity, price, advance and",
    { size: 9, color: grey, gap: 12 },
  );
  line("balance terms above. HarvestLink charges neither party any commission.", {
    size: 9,
    color: grey,
    gap: 14,
  });
  line("Generated by HarvestLink. A good-faith digital record. Fair & legal.", {
    size: 9,
    color: grey,
  });

  return pdf.save();
}
